name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - try

permissions: {}

env:
  flake: github:${{ github.repository }}/${{ github.sha }}
  cachix-name: vim-config
  nix-conf: |-
    accept-flake-config = true
    always-allow-substitutes = true
    builders-use-substitutes = true
    max-jobs = auto

jobs:
  flake-show:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm, macos-15 ]
    steps:
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: ${{ env.nix-conf }}
      - name: nix-flake-show
        run: nix flake show '${{ env.flake }}'

  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: ${{ env.nix-conf }}
      - id: gen-matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '${{ env.flake }}#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: build ${{ matrix.attr }}
    needs: [nix-matrix]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: ${{ env.nix-conf }}
      - uses: cachix/cachix-action@v15
        with:
          name: ${{ env.cachix-name }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: nix-fast-build
        run: |
          nix run '${{ env.flake }}#nix-fast-build' -- \
            --no-nom \
            --skip-cached \
            --option accept-flake-config true \
            --retries=3 \
            --flake='${{ env.flake }}#${{ matrix.attr }}'

  ci-ok:
    runs-on: ubuntu-latest
    needs: [ flake-show, nix-build ]
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: eval
